import Descriptions from "@/components/Descriptions";
import Navbar from "@/components/Navbar/Navbar";
import Title from "@/components/Title";
import useGradient from "@/hooks/useGradient";
import Head from "next/head";

function App() {
  const { current } = useGradient();

  const getShadowColor = () => {
    switch (current) {
      case 0:
        return "rgba(81, 194, 111, 0.2)";
      case 1:
        return "rgba(121, 40, 202, 0.2)";
      case 2:
        return "rgba(255, 77, 77, 0.2)";
      default:
        return "";
    }
  };
  const getBorderColor = () => {
    switch (current) {
      case 0:
        return "#51c26f";
      case 1:
        return "#7928CA";
      case 2:
        return "#FF4D4D";
      default:
        return "";
    }
  };

  const buttonStyle = {
    backgroundColor: "#000",
    border: `2px solid ${getBorderColor()}`,
    boxShadow: `0px 0px 16px 14px ${getShadowColor()}`,
    color: "#fff",
    transition:
      "border-color 0.5s ease-in-out, box-shadow 0.5s ease-in-out, color 0.5s ease-in-out",
    filter: `drop-shadow(0 0 5px ${getShadowColor()})`,
    cursor: "pointer",
  };

  return (
    <>
      <Head>
        <title>Bet You Win</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative h-screen" style={{ overflowX: "hidden" }}>
        <Navbar />
        <div
          className="bg-cover md:bg-center lg:bg-right h-full z-0 absolute inset-0 lg:translate-x-1/2"
          style={{
            backgroundImage: `url('/background.png')`,
          }}
        />
        <main className="absolute left-1/2 top-1/2 -translate-y-1/2 -translate-x-1/2">
          <Title current={current} title="Select" index={0} />
          <Title current={current} title="Bet" index={1} />
          <Title current={current} title="Manage" index={2} />
          <div className="flex flex-col items-center mt-20 space-y-10 justify-center">
            <p className="text-[#888] text-center text-xl tracking-tight">
              We are a team of sports enthusiasts, betting experts, and skilled
              developers who have come together to create a platform that will
              revolutionize your sports betting experience. Betyouwin is the
              first platform that allows you to challenge bookmakers on equal
              terms !
            </p>
            <span></span>
            <div
              className="px-10 py-3 rounded-md w-full md:w-48 text-center"
              style={buttonStyle}
            >
              Sign Up
            </div>
          </div>
        </main>
      </div>
      <Descriptions />

      <section className="bg-[#111] lg:border border-[#333] mt-36 text-center lg:flex lg:divide-x-[1px] space-y-10 md:space-y-0 divide-gray-500 items-center py-8">
        <div className="w-full flex-col items-center justify-center">
          <span className="font-bold tracking-tighter text-6xl">50</span>
          <p className="text-sm font-semibold text-[#888] uppercase">leagues</p>
        </div>
        <div className="w-full flex-col items-center justify-center">
          <span className="font-bold tracking-tighter text-6xl">35</span>
          <p className="text-sm font-semibold text-[#888] uppercase">
            countries
          </p>
        </div>
        <div className="w-full flex-col items-center justify-center">
          <span className="font-bold tracking-tighter text-6xl">
            100 fixtures
          </span>
          <p className="text-sm font-semibold text-[#888] uppercase">day</p>
        </div>
      </section>
    </>
  );
}

export default App;
